### ISSUE TITLE
build manuals for magit and related packages

### ISSUE THREAD

**Issue by marienz** [marienz/nix-doom-emacs-unstraightened#25]
See https://github.com/doomemacs/doomemacs/issues/8007#issuecomment-2302177459.

Previously, we installed magit.info (as part of emacs-magit-9999snapshot, into `share/emacs/site-lisp/elpa/magit-9999snapshot/magit.info`). After recent changes/bumps, we no longer do.

This will probably just take adding `make texi` in a preBuild hook for all of them: assuming their build system is like Magit's, the build target will already be there even if we're currently pinned to a rev with prebuilt docs.

I don't have time to fix this right now, filing myself an issue so I don't forget...

**Comment by panchoh** [comment]
FYI: https://github.com/doomemacs/doomemacs/issues/8007#issuecomment-2322080595

**Comment by marienz** [comment]
Ah, thanks for mentioning that! Looks like I won't need to make any changes after all, but I'll keep this open until we pull in versions with manuals again, just in case anyone misses them.

**Comment by marienz** [comment]
Closing, manuals are back after the last update.
