### ISSUE TITLE
Making packages like shellcheck accessible to Doom Emacs

### ISSUE THREAD

**Issue by KamWithK** [marienz/nix-doom-emacs-unstraightened#33]
I installed Doom Emacs as guided by the README, but can't seem to figure out how to make `shellcheck`, `pandoc`, `nixfmt`, etc available to Doom:

```nix
{ pkgs, config, ... }:

{
  programs.doom-emacs = {
    enable = true;
    doomDir = ../../dotfiles/doom;
    emacs = pkgs.emacs29-pgtk;
    extraPackages = epkgs: config.programs.emacs.extraPackages epkgs ++ [ epkgs.treesit-grammars.with-all-grammars ];
    extraBinPackages = with pkgs; [ git ripgrep fd shellcheck pandoc nixfmt-classic nodePackages.npm ];
  };
  services.emacs.enable = true;
}
```

What is the intended way to actually have Doom access these modules?
Any help would be greatly appreciated! Big thank you for creating this, very cool!

**Comment by KamWithK** [comment]
Nevermind I'm dumb and was rerunning the wrong flake... Figured it all out promptly after I realized lol

**Comment by CaptainJawZ** [comment]
When you say using the wrong flake what do you mean? I am having the same issue, but I think I set-up everything accordingly, if you could help me out, I'd appreciate it

**Comment by KamWithK** [comment]
> When you say using the wrong flake what do you mean? I am having the same issue, but I think I set-up everything accordingly, if you could help me out, I'd appreciate it

It was a short while ago but I was updating the system flake instead of my home manager one
