### ISSUE TITLE
Building Doom fails with "infinite recursion"

### ISSUE THREAD

**Issue by thecaralice** [marienz/nix-doom-emacs-unstraightened#38]
Building Doom fails on `doomEmacsPackages` phase if nixpkgs has https://github.com/NixOS/nixpkgs/commit/cf3f6beff7f7705fe1b1454ffedf0fccf4fb7aa1. Not sure if this is an NDEU issue or an emacs-overlay issue.

**Comment by marienz** [comment]
https://github.com/marienz/nix-doom-emacs-unstraightened/commit/f42213c85926350c31be8c37f162d05a5d7b1240 was supposed to fix this. If you're synced past that, I may need steps to reproduce (failing flake, including flake.lock) to track this one down.

**Comment by thecaralice** [comment]
Oh, nice, will try that
