### ISSUE TITLE
elisp-packages derivations may need src

### ISSUE THREAD

**Issue by marienz** [marienz/nix-doom-emacs-unstraightened#4]
Noticed while looking into #3.

Enabling scala but not org results in:

```
error: builder for '/nix/store/lhr33hvyg4wj1f52134cbq35rbvihiv1-emacs-org-1.drv' failed with exit code 1;
       last 2 log lines:
       > Running phase: unpackPhase
       > variable $src or $srcs should point to the source
       For full logs, run 'nix log /nix/store/lhr33hvyg4wj1f52134cbq35rbvihiv1-emacs-org-1.drv'.
```

Looks like something still pulls in org, which hits our custom derivation, but that derivation expects its src to be externally provided. Our dynamically-generated derivations have an assert for this but our custom derivations just fail.

Probably need to give these a default src to handle this.

Probably not common for org but there might be others with the same problem.

**Comment by charmoniumQ** [comment]
Thanks for developing this!

**Comment by marienz** [comment]
My pleasure!

Also, the changes I just pushed should fix this not just for org but more generally.
