### ISSUE TITLE
evil-escape missing in default install, but it's default doom module

### ISSUE THREAD

**Issue by RafalBabinicz** [marienz/nix-doom-emacs-unstraightened#41]
Firstly: love your work. Amazing.
Declaring modules in init.el *magic happens* and now **nix** installed them… that's first class experience. Thank you for it so much.

I'm still figuring out my way, but I see that evil-escape (default package in doom and evil module) is not available after installation.

Looking at https://github.com/doomemacs/doomemacs/blob/master/modules/editor/evil/packages.el it looks like packages defined with :recipe are absent from unstraightened—so evil-escape, evil-textobj-anyblock, evil-quick-diff—the rest is in path and installed.

Ofc, I can be wrong, still new to the setup. Cheers.

**Comment by marienz** [comment]
Glad you like it!

> I'm still figuring out my way, but I see that evil-escape (default package in doom and evil module) is not available after installation.

Wild guess: if you're testing Unstraightened by copying your config into this repository's `doomdir` (that is: you're following my ["test run"](https://github.com/marienz/nix-doom-emacs-unstraightened/?tab=readme-ov-file#test-run) instructions), and your config does not contain a packages.el, please delete my example packages.el and retry. If that's not it, please let me know and I will have a closer look.

(I use that doomdir for basic testing, so I had to disable some package, and I picked that one... The readme should really say "remove doomdir/* and then copy your config there", not just "copy your config and overwrite what's there", I'll fix that later...)

**Comment by marienz** [comment]
(...and packages with `:recipe` should work, and evil-quick-diff and evil-textobj-anyblock in particular look like they work.)

**Comment by RafalBabinicz** [comment]
What a silly goose I am. Ofc, evil-emacs is disabled in packages.el that I copied during initial setup from unstraightened's doomdir and never checked since, (only modified init.el).

anyblock and quickdiff are available, just do not expose any variables, so I mistakenly assumed they are not available.

Closing this as this was user error.

PS do you use a custom keyboard with Esc in convenient location that you have no need for evil-escape?

**Comment by RafalBabinicz** [comment]
User error in configuration, evil-scape was disabled in package.el with `(package! evil-escape :disable t)`
copied verbatim from 
`https://github.com/marienz/nix-doom-emacs-unstraightened/blob/main/doomdir/packages.el`

**Comment by marienz** [comment]
Tweaked the README to hopefully avoid others hitting this.

(And yeah, between having long fingers, using Emacs movement in insert mode (`evil-disable-insert-state-bindings t`) when I really should be switching to normal mode more, and usually using an ortholinear keyboard with Esc about between where ` and 1 are on a normal keyboard, I don't really need evil-escape myself...)
